config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'users#index'
  resources :users do
    resources :successes, only: [:create, :edit, :update, :destroy]
    resources :emotions, only: [:create, :edit, :update, :destroy]
    resources :messages, only: [:create, :edit, :update, :destroy]
    resources :notes, only: :create
  end

  resources :users, only: [:show, :edit, :destroy]

  resources :successes, only: :show do
    resource :likes, only: [:create, :destroy]
  end

  resources :emotions, only: :show #do
    #resource :likes, only: [:create, :destroy]
  #end

  resources :messages, only: :show do
    resources :comments, only: :create
    #resource :likes, only: [:create, :destroy]
  end

  resources :notes, only: :destroy

end

app/models/message.rb
class Message < ApplicationRecord

  with_options presence: true do
    validates :title
    validates :text
  end

  belongs_to :user
  has_many   :comments, dependent: :destroy
  has_many   :likes, dependent: :destroy
  has_many   :users, through: :likes

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, only: :create
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :move_to_top_page, only: [:edit, :update, :destroy]

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path
    else
      render "users/edit"
    end
  end

  def show
    @comment = Comment.new
    @comments = @message.comments.includes(:user)
  end

  def edit
    if user_signed_in?
      @user = User.find(current_user.id)
    end
  end

  def update
    if @message.update(message_params)
      redirect_to root_path
    else
      render :edit
    end    
  end

  def destroy
    if @message.destroy
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def message_params
    params.require(:message).permit(:title, :text).merge(user_id: params[:user_id])
  end

  def set_message
    @message = Message.find(params[:id]) 
  end

  def move_to_top_page
    unless current_user.id == @message.user_id
      redirect_to root_path
    end
  end 

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/edit.html.erb
<%= render "shared/header" %>

<h2 class="edit-page">編集ページ</h2>

<div class="contents-edit">

  <div class="right-contents">
    <h4 class="content-title">褒めちぎって欲しいこと投稿</h4>
    <div class="contents-form">
      <%= form_with(model: [@user, @message], local: true) do |f| %>

        <div class="form-title">タイトル</div>
        <%= f.text_area :title, class: "title-field", placeholder: "例）私を褒めちぎって下さい" %>
        <div class="form-text">内容</div>
        <%= f.text_area :text, class: "text-field", placeholder: "具体的に褒めちぎって欲しい事を遠慮なく載せよう！！" %>

        <div class="form-btn">
          <%= f.submit "更新", id: "form-submit" %>
        </div>

      <% end %>
    </div>
  </div>

</div>

<%= render "shared/footer" %>

app/views/messages/show.html.erb
<%= render "shared/header" %>

<div class="contents-show">

  <div class="content-show">
    <div class="title-show">タイトル</div>
    <%= @message.title %>
    <div class="text-show">内容</div>
    <%= @message.text %>
    <div class="user-show">投稿者</div>
    <%= "by#{@message.user.nickname}さん" %>
  </div>

  <div class="show-btn">
    <% if user_signed_in? && current_user.id == @message.user_id %>
      <%= link_to "編集", edit_user_message_path(@message.id), class: "edit-btn" %>
      <p class="or-text">or</p>
      <%= link_to "削除", user_message_path(@message.id), method: :delete, class: "delete-btn" %>
    <% else %>
      <div class="good-btn">いいね！</div>
    <% end %>
  </div>

  <div class="message-comments">
    <% if user_signed_in? && current_user.id != @message.user_id%>
      <%= form_with(model: [@message, @comment], class: "comments-form", local: true) do |f| %>
        <div class="field">
          <%= f.text_field :text, class:"comment-field", placeholder: "コメントを入力" %>
        </div>
        <div class="actions">
          <%= f.submit "送信", class: "comment-btn"  %>
        </div>
      <% end %>
    <% end %>

    <ul class="comments-lists">
      <% @comments.reverse_each do |comment| %>
        <li class="comments_list">
          <%= comment.text %>
          <%= "by#{comment.user.nickname}さん" %>
        </li>
      <% end %>
    </ul>
  </div>

</div>

<%= render "shared/footer" %>