config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'users#index'
  resources :users do
    resources :successes, only: [:create, :edit, :update, :destroy]
    resources :emotions, only: [:create, :edit, :update, :destroy]
    resources :messages, only: [:create, :edit, :update, :destroy]
    resources :notes, only: :create
  end

  resources :users, only: [:show, :edit, :destroy]

  resources :successes, only: :show do
    resource :likes, only: [:create, :destroy]
  end

  resources :emotions, only: :show #do
    #resource :likes, only: [:create, :destroy]
  #end

  resources :messages, only: :show do
    resources :comments, only: :create
    #resource :likes, only: [:create, :destroy]
  end

  resources :notes, only: :destroy

end

app/models/emotion.rb
class Emotion < ApplicationRecord

  with_options presence: true do
    validates :title
    validates :text
  end

  belongs_to :user
  has_many   :likes, dependent: :destroy
  has_many   :users, through: :likes
  
end

app/controllers/emotions_controller.rb
class EmotionsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  before_action :set_emotion, only: [:show, :edit, :update, :destroy]
  before_action :move_to_top_page, only: [:edit, :update, :destroy]
  
  def create
    @emotion = Emotion.new(emotion_params)
    if @emotion.save
      redirect_to root_path
    else
      render "users/edit"
    end
  end

  def show

  end

  def edit
    if user_signed_in?
      @user = User.find(current_user.id)
    end
  end

  def update
    if @emotion.update(emotion_params)
      redirect_to root_path
    else
      render :edit
    end    
  end

  def destroy
    if @emotion.destroy
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def emotion_params
    params.require(:emotion).permit(:title, :text).merge(user_id: params[:user_id])
  end

  def set_emotion
    @emotion = Emotion.find(params[:id]) 
  end

  def move_to_top_page
    unless current_user.id == @emotion.user_id
      redirect_to root_path
    end
  end

end

app/helpers/emotions_helper.rb
module EmotionsHelper
end

app/views/emotions/edit.html.erb
<%= render "shared/header" %>

<h2 class="edit-page">編集ページ</h2>

<div class="contents-edit">

  <div class="right-contents">
    <h4 class="content-title">情緒的喚起投稿</h4>
    <div class="contents-form">
      <%= form_with(model: [@user, @emotion], local: true) do |f| %>

        <div class="form-title">タイトル</div>
        <%= f.text_area :title, class: "title-field", placeholder: "例）私が情緒的喚起できること" %>
        <div class="form-text">内容</div>
        <%= f.text_area :text, class: "text-field", placeholder: "あなたが情緒的喚起できることを投稿しましょう！！" %>

        <div class="form-btn">
          <%= f.submit "更新", id: "form-submit" %>
        </div>

      <% end %>
    </div>
  </div>

</div>

<%= render "shared/footer" %>

app/views/emotions/show.html.erb
<%= render "shared/header" %>

<div class="contents-show">

  <div class="content-show">
    <div class="title-show">タイトル</div>
    <%= @emotion.title %>
    <div class="text-show">内容</div>
    <%= @emotion.text %>
    <div class="user-show">投稿者</div>
    <%= "by#{@emotion.user.nickname}さん" %>
  </div>

  <div class="show-btn">
    <% if user_signed_in? && current_user.id == @emotion.user_id %>
      <%= link_to "編集", edit_user_emotion_path(@emotion.id), class: "edit-btn" %>
      <p class="or-text">or</p>
      <%= link_to "削除", user_emotion_path(@emotion.id), method: :delete, class: "delete-btn" %>
    <% else %>
      <div class="good-btn">いいね！</div>
    <% end %>
  </div>

</div>

<%= render "shared/footer" %>