config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'users#index'
  resources :users do
    resources :successes, only: [:create, :edit, :update, :destroy]
    resources :emotions, only: [:create, :edit, :update, :destroy]
    resources :messages, only: [:create, :edit, :update, :destroy]
    resources :notes, only: :create
  end

  resources :users, only: [:show, :edit, :destroy]

  resources :successes, only: :show do
    resource :likes, only: [:create, :destroy]
  end

  resources :emotions, only: :show #do
    #resource :likes, only: [:create, :destroy]
  #end

  resources :messages, only: :show do
    resources :comments, only: :create
    #resource :likes, only: [:create, :destroy]
  end

  resources :notes, only: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :message

  validates :text, presence: true
end

app/models/emotion.rb
class Emotion < ApplicationRecord

  with_options presence: true do
    validates :title
    validates :text
  end

  belongs_to :user
  has_many   :likes, dependent: :destroy
  has_many   :users, through: :likes
  
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :success
  #belongs_to :message
  #belongs_to :emotion

end

app/models/message.rb
class Message < ApplicationRecord

  with_options presence: true do
    validates :title
    validates :text
  end

  belongs_to :user
  has_many   :comments, dependent: :destroy
  has_many   :likes, dependent: :destroy
  has_many   :users, through: :likes

end

app/models/note.rb
class Note < ApplicationRecord

  validates :comment, presence: true

  belongs_to :user
  
end

app/models/success.rb
class Success < ApplicationRecord

  with_options presence: true do
    validates :title
    validates :text
  end

  belongs_to :user
  has_many   :likes, dependent: :destroy
  has_many   :users, through: :likes
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many         :successes, dependent: :destroy
  has_many         :emotions,  dependent: :destroy
  has_many         :messages,  dependent: :destroy
  has_many         :notes,     dependent: :destroy
  has_many         :comments,  dependent: :destroy
  has_many         :likes,     dependent: :destroy
  has_many         :like_successes, through: :likes, source: :success
  has_many         :like_emotions,  through: :likes, source: :emotion
  has_many         :like_messages,  through: :likes, source: :message

  with_options presence: true do
    validates :image
    validates :nickname
    validates :name,format: {with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: "は全角（漢字・ひらがな・カタカナ）入力のみ可能です" }
    validates :birthday
    validates :phone, format: { with: /\A[0-9]{10,11}\z/, message: "は半角数字（ハイフンは含まない）入力のみ可能です" }
  end

  validates :password, format: {with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: "は半角（英字・数字）の混合入力のみ可能です" }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
      if @comment.save
        redirect_to message_path(@comment.message)
      else
        render "users/edit"
      end    
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, message_id: params[:message_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :set_success, only: [:show]

  def create
    unless current_user.like_successes.include?(clicked_success)
      like = current_user.likes.new(success_id: clicked_success.id)
      if like.save
        redirect_to success_path(like.success)
      else
        render "users/edit"
      end
    end
  end

  def destroy
    current_user.likes.find_by(success_id: params[:success_id]).destroy
    redirect_to root_path
  end

  private

  def clicked_success
    Success.find(params[:success_id])
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @note = Note.new(note_params)
    if @note.save
      ActionCable.server.broadcast 'note_channel', content: @note
    else
      redirect_to root_path
    end
  end

  def destroy
    if user_signed_in?
      @user = User.find(current_user.id)
    end
    if @user.notes.destroy_all
      redirect_to root_path
    else
      render :edit
    end     
  end

  private

  def note_params
    params.require(:note).permit(:comment).merge(user_id: params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :destroy]

  def index
    if user_signed_in?
      @user = User.find(current_user.id)
    end
    @success = Success.new
    @successes = Success.all.order("created_at DESC")
    
    @emotion = Emotion.new
    @emotions = Emotion.all.order("created_at DESC")

    @message = Message.new
    @messages = Message.all.order("created_at DESC")

    @note = Note.new
    @notes = Note.all
  end

  def show
    
  end

  def edit
    
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to root_path
    else
      render :show
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/emotions_helper.rb
module EmotionsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/successes_helper.rb
module SuccessesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Selfy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_emotion.html.erb
<div class="common-contents">

  <div class="left-contents">
    <h4 class="content-title">情緒的喚起一覧</h4>

    <p id="content-lists">
      <% @emotions.each do |emotion| %>
        <p class="content-list">
          <%= emotion.created_at.strftime('%Y/%m/%d %H:%M') %>
          <%= link_to emotion.title, emotion_path(emotion.id), class: "contents-title" %>
          <%= "by #{emotion.user.nickname}さん" %>
        </p>
      <% end %>
    </p>    
  </div>

  <div class="right-contents">
    <h4 class="content-title">情緒的喚起投稿</h4>
    <div class="contents-form">
      <%= form_with(model: [@user, @emotion], local: true) do |f| %>

        <div class="form-title">タイトル</div>
        <%= f.text_area :title, class: "title-field", placeholder: "例）私が情緒的喚起できること" %>
        <div class="form-text">内容</div>
        <%= f.text_area :text, class: "text-field", placeholder: "あなたが情緒的喚起できることを投稿しましょう！！" %>

        <div class="form-btn">
          <%= f.submit "投稿", id: "form-submit" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

  <div class="footer-top">
    <div class="footer-left">
      <p><%= link_to "会社概要", "#", class: "footer-link" %></p>
      <p><%= link_to "プライバシーポリシー", "#", class: "footer-link" %></p>
      <p><%= link_to "利用規約", "#", class: "footer-link" %></p>
    </div>
    <div class="footer-right">
      <p><%= link_to "採用情報", "#", class: "footer-link" %></p>
      <p><%= link_to "引用書籍・サイト", "#", class: "footer-link" %></p>
      <p><%= link_to "作成者", "#", class: "footer-link" %></p>
    </div>
  </div>

  <div class="footer-bottom">
    © SELFY
  </div>
</div>

app/views/shared/_header.html.erb
<header class="top-page-header">

  <div class="nav">
    <div class="header-left">
      <%= link_to image_tag("logo.jpeg" , class: "header-logo"), "/" %>
      <div class="header-center">
        〜あなたの自己効力感向上の手助けをします〜
      </div>
    </div>

    <div class="header-right">
      <ul class="user-devise">
        <% if user_signed_in? %>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete,  class: "logout" %></li>
          <li><%= link_to "退会", user_path(current_user.id), class: "unsubscribe" %></li>
        <% else %>
          <li><%= link_to "ログイン", new_user_session_path, class: "login" %></li>
          <li><%= link_to "新規登録", new_user_registration_path, class: "sign-up" %></li>
        <% end %>
      </ul>
    </div>
  </div>

</header>

app/views/shared/_message.html.erb
<div class="common-contents">

  <div class="left-contents">
    <h4 class="content-title">褒めちぎって欲しいこと一覧</h4>

    <p id="content-lists">
      <% @messages.each do |message| %>
        <p class="content-list">
          <%= message.created_at.strftime('%Y/%m/%d %H:%M') %>
          <%= link_to message.title, message_path(message.id), class: "contents-title" %>
          <%= "by #{message.user.nickname}さん" %>
        </p>
      <% end %>
    </p>
  </div>

  <div class="right-contents">
    <h4 class="content-title">褒めちぎって欲しいこと投稿</h4>
    <div class="contents-form">
      <%= form_with(model: [@user, @message], local: true) do |f| %>

        <div class="form-title">タイトル</div>
        <%= f.text_area :title, class: "title-field", placeholder: "例）私を褒めちぎって下さい" %>
        <div class="form-text">内容</div>
        <%= f.text_area :text, class: "text-field", placeholder: "具体的に褒めちぎって欲しい事を遠慮なく載せよう！！" %>

        <div class="form-btn">
          <%= f.submit "投稿", id: "form-submit" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/shared/_my_page.html.erb
<div class="my-page">

  <div class="my-image">
    <div class="profile-content">プロフィール画像</div>
    <%= image_tag current_user.image, class: "my-page-image" if current_user.image.attached? %>
  </div>


  <div class="my-profile">
    <div class="profile-content">ユーザー情報</div>
    <div class="profile-content">ユーザー名</div>
      <div><%= current_user.nickname %></div>
    <div class="profile-content">本名</div>
      <div><%= current_user.name %></div>
    <div class="profile-content">メールアドレス</div>
      <div><%= current_user.email %></div>
    <div class="profile-content">生年月日</div>
      <div><%= current_user.birthday.strftime('%Y/%m/%d') %></div>
    <div class="profile-content">電話番号</div>
      <div><%= current_user.phone %></div>
  </div>

</div>

app/views/shared/_note.html.erb
<div class="my-note">

  <div class="message-form">
    <%= form_with(model: [@user, @note], local: true) do |f| %>
      <%= f.text_field :comment, placeholder: 'メッセージを入力', class: 'comment-field' %>
      <%= f.submit '送信', id: 'note-submit' %>
      <%= link_to '一括削除', note_path(@user), method: :delete, id: 'delete' %>
    <% end %>
  </div>

  <div id='notes'>
    <% @notes.each do |note| %>
      <% if current_user.id == note.user_id %>
        <P><%= note.comment %></p>
      <% end %>
    <% end %>
  </div>

</div>

app/views/shared/_success.html.erb
<div class="common-contents">

  <div class="left-contents">
    <h4 class="content-title">成功体験一覧</h4>

    <p id="content-lists">
      <% @successes.each do |success| %>
        <p class="content-list">
          <%= success.created_at.strftime('%Y/%m/%d %H:%M') %>
          <%= link_to success.title, success_path(success.id), class: "contents-title" %>
          <%= "by #{success.user.nickname}さん" %>
        </p>
      <% end %>
    </p>
  </div>

  <div class="right-contents">
    <h4 class="content-title">成功体験投稿</h4>
    <div class="contents-form">
      <%= form_with(model: [@user, @success], local: true) do |f| %>

        <div class="form-title">タイトル</div>
        <%= f.text_area :title, class: "title-field", placeholder: "例）私が転職に成功した話" %>
        <div class="form-text">内容</div>
        <%= f.text_area :text, class: "text-field", placeholder: "あなたの成功体験を好きなように投稿しましょう！！" %>

        <div class="form-btn">
          <%= f.submit "投稿", id: "form-submit" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/shared/_top_page.html.erb
<div class="top-page">

  <div class="application-explanation">
    <div class="box">
      <span class="box-title">〜SELFY〜</span>
      <div class="">
        このアプリケーションは、あなたの自己効力感向上の手助けをします。<br>
       「自己効力感」とは、人が行動や成果を求められる状況下において、「自分は必要な行動をとって、結果を出せる」と考えられる力を言います。<br>
        簡単に言うと、「自分にはできる！！」と自信や確信に満ちた状態であることです。<br>
        SELFYでは、自己効力感の向上に重要なポイントに添ってコンテンツを展開しております。<br>
        各コンテンツを使用して、是非あなたが少しでも前向きな気持ちになれるよう、お気軽にご利用下さい。<br>
      </div>
    </div>
  </div>
  
  <div class="top-explanation">
    <div class="box">
      <span class="box-title">成功体験</span>
      <div class="">
        成功体験コンテンツでは、「成功経験を積むこと」「他の人の成功体験を見聞きするこ<br>
        と」というポイントに基づいております。<br>
        自身で何かを達成する、成功するという体験は、最も強く自己効力感を向上させます。<br>
        また、他の誰かの成功体験を見聞きすることで、自分にも出来るのではないか、と感じ<br>
        ることです。<br>
        ポイントは、「自分と似た状態の誰か・経験」を見つけることです。<br>
        是非あなたの成功体験を投稿して、皆さんに共有しましょう。
      </div>
    </div>
    <div class="box">
      <span class="box-title">褒めちぎり</span>    
      <div class="">
        褒めちぎりコンテンツでは、「自分には能力がある、と言ってもらう」というポイント<br>
        に基づいております。また、作成者である私のこだわりで、とにかく褒めちぎってもら<br>
        って気分を上げていきたい、という時に使って欲しいです。<br>
        周りからの励ましや評価、実際に言葉として言ってもらうことで、自身の良いところを<br>
        知り、前向きになれます。<br>
        ここでの一つのルールは、「相手の気分がマイナスになるようなことは絶対に言わない<br>
        こと」です。相手を非難したり強い口調で否定したりするようなことはおやめ下さい。<br>
        是非あなたの言葉でまだ見ぬ誰かを、とにかく褒めちぎってあげてください。<br>
      </div>
    </div>
  </div>

  <div class="bottom-explanation">
    <div class="box">
      <span class="box-title">情緒的喚起</span>
      <div class="">
        情緒的喚起コンテンツでは、「生理的・感情的」というポイントに基づいております。<br>
        簡単に言うと、気分や気持ちによって変わると言うことです。例えば、好きな音楽を <br>
        聴いている時は気持ちが上がる、思い切って好きなことをたくさんする、どんなこと <br>
        でも良いんです。<br>
        是非あなたの感情や生理的な変化が起こる出来事を、皆さんへ共有してみましょう。 <br>
      </div>
    </div>

    <div class="box">
      <span class="box-title">My Note</span>
      <div class="">
        My Noteコンテンツでは、「メモ書き」というポイントに基づいております。<br>
        これは、「0秒思考：頭がよくなる世界一シンプルなトレーニング」という有名な本か<br>
        ら着想を得たものです。本来はA4用紙に短い時間で直接メモ書きを行い、思考の言語<br>
        化を行います。<br>
        しかし、SELFYでは他の各コンテンツと併用して使ってもらうことで、自己効力感向上<br>
        の相乗効果を狙っています。<br>
        メモ書きを行い、思考の整理・言語化を行うもよし。単なるメモ帳代わりに使っても<br>
        よし。使い方はあなた次第です。<br>
      </div>
    </div>
  </div>

</div>