config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'users#index'
  resources :users do
    resources :successes, only: [:create, :edit, :update, :destroy]
    resources :emotions, only: [:create, :edit, :update, :destroy]
    resources :messages, only: [:create, :edit, :update, :destroy]
    resources :notes, only: :create
  end

  resources :users, only: [:show, :edit, :destroy]

  resources :successes, only: :show do
    resource :likes, only: [:create, :destroy]
  end

  resources :emotions, only: :show #do
    #resource :likes, only: [:create, :destroy]
  #end

  resources :messages, only: :show do
    resources :comments, only: :create
    #resource :likes, only: [:create, :destroy]
  end

  resources :notes, only: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :message

  validates :text, presence: true
end

app/models/emotion.rb
class Emotion < ApplicationRecord

  with_options presence: true do
    validates :title
    validates :text
  end

  belongs_to :user
  has_many   :likes, dependent: :destroy
  has_many   :users, through: :likes
  
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :success
  #belongs_to :message
  #belongs_to :emotion

end

app/models/message.rb
class Message < ApplicationRecord

  with_options presence: true do
    validates :title
    validates :text
  end

  belongs_to :user
  has_many   :comments, dependent: :destroy
  has_many   :likes, dependent: :destroy
  has_many   :users, through: :likes

end

app/models/note.rb
class Note < ApplicationRecord

  validates :comment, presence: true

  belongs_to :user
  
end

app/models/success.rb
class Success < ApplicationRecord

  with_options presence: true do
    validates :title
    validates :text
  end

  belongs_to :user
  has_many   :likes, dependent: :destroy
  has_many   :users, through: :likes
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many         :successes, dependent: :destroy
  has_many         :emotions,  dependent: :destroy
  has_many         :messages,  dependent: :destroy
  has_many         :notes,     dependent: :destroy
  has_many         :comments,  dependent: :destroy
  has_many         :likes,     dependent: :destroy
  has_many         :like_successes, through: :likes, source: :success
  has_many         :like_emotions,  through: :likes, source: :emotion
  has_many         :like_messages,  through: :likes, source: :message

  with_options presence: true do
    validates :image
    validates :nickname
    validates :name,format: {with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: "は全角（漢字・ひらがな・カタカナ）入力のみ可能です" }
    validates :birthday
    validates :phone, format: { with: /\A[0-9]{10,11}\z/, message: "は半角数字（ハイフンは含まない）入力のみ可能です" }
  end

  validates :password, format: {with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: "は半角（英字・数字）の混合入力のみ可能です" }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
      if @comment.save
        redirect_to message_path(@comment.message)
      else
        render "users/edit"
      end    
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, message_id: params[:message_id])
  end
end

app/controllers/emotions_controller.rb
class EmotionsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  before_action :set_emotion, only: [:show, :edit, :update, :destroy]
  before_action :move_to_top_page, only: [:edit, :update, :destroy]
  
  def create
    @emotion = Emotion.new(emotion_params)
    if @emotion.save
      redirect_to root_path
    else
      render "users/edit"
    end
  end

  def show

  end

  def edit
    if user_signed_in?
      @user = User.find(current_user.id)
    end
  end

  def update
    if @emotion.update(emotion_params)
      redirect_to root_path
    else
      render :edit
    end    
  end

  def destroy
    if @emotion.destroy
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def emotion_params
    params.require(:emotion).permit(:title, :text).merge(user_id: params[:user_id])
  end

  def set_emotion
    @emotion = Emotion.find(params[:id]) 
  end

  def move_to_top_page
    unless current_user.id == @emotion.user_id
      redirect_to root_path
    end
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :set_success, only: [:show]

  def create
    unless current_user.like_successes.include?(clicked_success)
      like = current_user.likes.new(success_id: clicked_success.id)
      if like.save
        redirect_to success_path(like.success)
      else
        render "users/edit"
      end
    end
  end

  def destroy
    current_user.likes.find_by(success_id: params[:success_id]).destroy
    redirect_to root_path
  end

  private

  def clicked_success
    Success.find(params[:success_id])
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @note = Note.new(note_params)
    if @note.save
      ActionCable.server.broadcast 'note_channel', content: @note
    else
      redirect_to root_path
    end
  end

  def destroy
    if user_signed_in?
      @user = User.find(current_user.id)
    end
    if @user.notes.destroy_all
      redirect_to root_path
    else
      render :edit
    end     
  end

  private

  def note_params
    params.require(:note).permit(:comment).merge(user_id: params[:user_id])
  end
end

app/controllers/successes_controller.rb
class SuccessesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  before_action :set_success, only: [:show, :edit, :update, :destroy]
  before_action :move_to_top_page, only: [:edit, :update, :destroy]

  def create
    @success = Success.new(success_params)
    if @success.save
      redirect_to root_path
    else
      render "users/edit"
    end
  end

  def show
    @like = Like.new
  end

  def edit
    if user_signed_in?
      @user = User.find(current_user.id)
    end
  end

  def update
    if @success.update(success_params)
      redirect_to root_path
    else
      render :edit
    end    
  end

  def destroy
    if @success.destroy
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def success_params
    params.require(:success).permit(:title, :text).merge(user_id: params[:user_id])
  end

  def set_success
    @success = Success.find(params[:id]) 
  end

  def move_to_top_page
    unless current_user.id == @success.user_id
      redirect_to root_path
    end
  end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :destroy]

  def index
    if user_signed_in?
      @user = User.find(current_user.id)
    end
    @success = Success.new
    @successes = Success.all.order("created_at DESC")
    
    @emotion = Emotion.new
    @emotions = Emotion.all.order("created_at DESC")

    @message = Message.new
    @messages = Message.all.order("created_at DESC")

    @note = Note.new
    @notes = Note.all
  end

  def show
    
  end

  def edit
    
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to root_path
    else
      render :show
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/emotions_helper.rb
module EmotionsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/successes_helper.rb
module SuccessesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/successes/edit.html.erb
<%= render "shared/header" %>

<h2 class="edit-page">編集ページ</h2>

<div class="contents-edit">

  <div class="right-contents">
    <h4 class="content-title">成功体験投稿</h4>
    <div class="contents-form">
      <%= form_with(model: [@user, @success], local: true) do |f| %>

        <div class="form-title">タイトル</div>
        <%= f.text_area :title, class: "title-field", placeholder: "例）私が転職に成功した話" %>
        <div class="form-text">内容</div>
        <%= f.text_area :text, class: "text-field", placeholder: "あなたの成功体験を好きなように投稿しましょう！！" %>

        <div class="form-btn">
          <%= f.submit "更新", id: "form-submit" %>
        </div>

      <% end %>
    </div>
  </div>

</div>

<%= render "shared/footer" %>

app/views/successes/show.html.erb
<%= render "shared/header" %>

<div class="contents-show">

  <div class="content-show">
    <div class="title-show">タイトル</div>
    <%= @success.title %>
    <div class="text-show">内容</div>
    <%= @success.text %>
    <div class="user-show">投稿者</div>
    <%= "by#{@success.user.nickname}さん" %>
  </div>

  <div class="show-btn">
    <% if user_signed_in? && current_user.id == @success.user_id %>
      <%= link_to "編集", edit_user_success_path(@success.id), class: "edit-btn" %>
      <p class="or-text">or</p>
      <%= link_to "削除", user_success_path(@success.id), method: :delete, class: "delete-btn" %>
    <% else %>
      <% if current_user.like_successes.include?(@success) %>
        <%= form_with(model: @like, url: success_likes_path(@success.id), method: :delete, local: true) do |f| %>
          <%= f.hidden_field :success_id, value: @success.id %>
          <%= f.submit 'いいね解除', class: "good-btn" %>
          <%= @success.likes.count(@success.id) %>
        <% end %>
      <% else %>
        <%= form_with(model: @like, url: success_likes_path(@success.id), local: true) do |f| %>
          <%= f.hidden_field :success_id, value: @success.id %>
          <%= f.submit 'いいね！', class: "good-btn" %>
          <%= @success.likes.count(@success.id) %>
        <% end %>
      <% end %>
      
    <% end %>

  </div>

</div>

<%= render "shared/footer" %>